version: '3.8'

services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME:-admin}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD:-password}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG:-myorg}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET:-bng-bucket}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN:-mytoken123}
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
    networks:
      - bng-network
    restart: unless-stopped

  bng-simulator:
    build:
      context: ./bng-simulator
      dockerfile: Dockerfile
    container_name: bng-simulator
    ports:
      - "50051:50051"
    networks:
      - bng-network
    restart: unless-stopped
    depends_on:
      - influxdb
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; socket.create_connection(('localhost', 50051), timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3

  telegraf:
    image: telegraf:1.28-alpine
    container_name: telegraf
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - bng-network
    depends_on:
      bng-simulator:
        condition: service_healthy
      influxdb:
        condition: service_started
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.1.0
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - bng-network
    depends_on:
      - influxdb
    restart: unless-stopped

  jupyter:
    build:
      context: ./jupyter
      dockerfile: Dockerfile
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter/notebooks:/home/jovyan/notebooks
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN:-mytoken123}
      - INFLUXDB_ORG=${INFLUXDB_ORG:-myorg}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET:-bng-bucket}
    networks:
      - bng-network
    depends_on:
      - influxdb
    restart: unless-stopped

volumes:
  influxdb-data:
  grafana-data:

networks:
  bng-network:
    driver: bridge