{
 "title": "BNG Subscriber Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Active Subscribers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bng-bucket\")\n  |> range(v.timeRangeStart, v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"bng_subscriber_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"state\" and r.state == \"ACTIVE\")\n  |> last()\n  |> group()\n  |> count()"
    }
   ]
  },
  {
   "title": "Total Bandwidth (bps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"bng-bucket\")\n  |> range(v.timeRangeStart, v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"bng_subscriber_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"input_octets\" or r[\"_field\"] == \"output_octets\")\n  |> aggregateWindow(every: v.windowPeriod, fn: increase, createEmpty: false)\n  |> group()\n  |> sum()\n  |> map(fn: (r) => ({ r with _value: r._value / float(v: v.windowPeriod) * 8.0}))\n"
    }
   ]
  },
  {
   "title": "Top Subscribers by Input Traffic",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"bng-bucket\")\n|> range(v.timeRangeStart, v.timeRangeStop)\n|> filter(fn: (r) => r[\"_measurement\"] == \"bng_subscriber_stats\" and r[\"_field\"] == \"input_octets\")\n|> increase()\n|> group(columns: [\"mac\"])\n|> sum()\n|> sort(columns: [\"_value\"], desc: true)\n|> limit(n: 50)\n"
    }
   ]
  }
 ]
}