apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    user: admin
    secureJsonData:
      token: mytoken123456789
    jsonData:
      version: Flux
      organization: myorg
      defaultBucket: bng-bucket
      tlsSkipVerify: true